# Generated by Django 4.0.4 on 2022-05-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('EQ', 'Equipamentos'), ('POT', 'Poções'), ('IT', 'Items')], default='IT', max_length=3)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
