# Generated by Django 4.0.4 on 2022-05-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Armas', (('Melee', 'Melee'), ('Ranged', 'Ranged'))), ('Armaduras', (('Helmet', 'Helmet'), ('Body Armor', 'Body Armor'))), ('Acessórios', (('Amuletos', 'Amuletos'), ('Anéis', 'Anéis'), ('Capas', 'Capas'), ('Braceletes', 'Braceletes'), ('Botas', 'Botas'))), ('Consumíveis', (('Poções', 'Poções'), ('Scrolls', 'Scrolls'), ('Varinhas', 'Varinhas'))), ('Outros', (('Input Livre', 'Input Livre'),))], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
