# Generated by Django 4.0.4 on 2022-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('Armas', (('Melee', 'Melee'), ('Ranged', 'Ranged'))), ('Armaduras', (('Helmet', 'Helmet'), ('Body Armor', 'Body Armor'))), ('Acessórios', (('Amuletos', 'Amuletos'), ('Anéis', 'Anéis'), ('Botas', 'Botas'), ('Braceletes', 'Braceletes'), ('Capas', 'Capas'))), ('Consumíveis', (('Poções', 'Poções'), ('Scrolls', 'Scrolls'), ('Varinhas', 'Varinhas'))), ('Outros', (('Input Livre', 'Input Livre'),))], max_length=20),
        ),
    ]
