# Generated by Django 4.0.4 on 2022-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_inventory_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(blank=True, choices=[('EQUIPMENTS', 'Equipamentos'), ('POTIONS', 'Poções'), ('ITEMS', 'Items')], max_length=10),
        ),
    ]
