# Generated by Django 4.0.4 on 2022-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_inventory_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(blank=True, choices=[('EQUIPMENTS', 'Equipamentos'), ('POTIONS', 'Poções'), ('ITEMS', 'Items')], max_length=50),
        ),
    ]
