# Generated by Django 4.0.4 on 2022-05-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_student_alter_inventory_item_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
