# Generated by Django 4.0.4 on 2022-05-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_inventory_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Armas', (('melee', 'Melee'), ('ranged', 'Ranged'))), ('Armaduras', (('helmet', 'Helmet'), ('body armor', 'Body Armor'), ('acessórios', 'Acessórios'))), ('Consumíveis', (('poções', 'Poções'), ('scrolls', 'Scrolls'), ('varinhas', 'Varinhas'), ('outros', 'Outros')))], max_length=50),
        ),
    ]
