# Generated by Django 4.0.4 on 2022-05-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_inventory_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(choices=[('Armas', (('melee', 'Melee'), ('ranged', 'Ranged'))), ('Armaduras', (('helmet', 'Helmet'), ('body armor', 'Body Armor'))), ('Acessórios', (('amuletos', 'Amuletos'), ('anéis', 'Anéis'), ('capas', 'Capas'), ('braceletes', 'Braceletes'), ('botas', 'Botas'))), ('Consumíveis', (('poções', 'Poções'), ('scrolls', 'Scrolls'), ('varinhas', 'Varinhas'))), ('Outros', (('input livre', 'Input Livre'),))], max_length=50),
        ),
    ]
